beats/urls.py
from django.urls import path
from . import views

app_name = 'beats'

urlpatterns = [
]

rhyme/urls.py
from django.contrib import admin
from django.urls import path, include
from rhyme import views
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('verses/', include('verses.urls')),
    path('beats/', include('beats.urls')),
    path('rhymers/', include('users.urls')),
    path('notifications/', include('notifications.urls')),
    path('', views.home, name='home'),
    path('help/', views.help, name='help'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('search/', views.search, name='search'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('<int:user_id>',  views.detail, name = 'detail'),
    path('<int:user_id>/likes',  views.likes, name = 'likes'),
    path('<int:user_id>/edit', views.edit, name = 'edit'),
    path('<int:user_id>/follow', views.follow, name = 'follow'),
    path('<int:user_id>/unfollow', views.unfollow, name = 'unfollow'),
    path('<int:user_id>/followers', views.show_followers, name = 'followers'),
    path('<int:user_id>/follows', views.show_follows, name = 'follows'),
    path('<int:user_id>/notification', views.notification, name='notification'),
]

verses/urls.py
from django.urls import path
from . import views
from .views import PostLikeToggle, PostLikeAPIToggle

app_name = 'verses'

urlpatterns = [
    path('create/',  views.create, name = 'create'),
    path('index/', views.index, name='index'),
    path('<int:verse_id>',views.detail, name='detail'),
    path('<int:verse_id>/delete',views.delete, name='delete'),
    path('<int:verse_id>/like/',PostLikeToggle.as_view(), name='like'),
    path('api/<int:verse_id>/like/',PostLikeAPIToggle.as_view(), name='like-api'),
    path('<int:verse_id>/answer/',views.answer, name = 'answer'),
    path('<int:verse_id>/beef/',views.beef, name = 'beef'),
]

rhyme/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from verses.models import Verse
from users.models import User
import operator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from itertools import chain


def home(request):
    if request.user.is_authenticated:
        user = request.user
        followees = user.get_follows();
        verse_list = Verse.objects.filter(rhymer = user)
        for followee in followees:
            followee_verses = Verse.objects.filter(rhymer = followee)
            verse_list = list(chain(verse_list, followee_verses))
        if len(verse_list) == 0:
            return redirect('/verses/index')
        verse_list = sorted(verse_list, key = operator.attrgetter('pub_date'), reverse = True)
        page = request.GET.get('page',1)
        paginator = Paginator(verse_list, 15)
        try:
            verses = paginator.page(page)
        except PageNotAnInteger:
            verses = paginator.page(1)
        except EmptyPage:
            verses = paginator.page(paginator.num_pages)
        return render(request, 'timeline.html', {'verses':verses})
    else:
        return render(request, 'home.html')

def help(request):
    return render(request, 'help.html')

def privacy(request):
    return render(request,'privacy.html')

def terms(request):
    return render(request, 'terms.html')

def search(request):
    page = request.GET.get('page',1)
    if request.method == 'POST':
        if request.POST['w']:
            results_list = Verse.objects.filter(body__contains = request.POST['w']).order_by('-pub_date')
            paginator = Paginator(results_list, 15)
            try:
                results = paginator.page(page)
            except PageNotAnInteger:
                results = paginator.page(1)
            except EmptyPage:
                results = paginator.page(paginator.num_pages)
            return render(request, 'search.html', {'results': results})
        else:
            return render(request, 'search.html', {'error': 'Please enter some word'})
    else:
        trends_list = Verse.objects.order_by('-pub_date')
        paginator = Paginator(trends_list, 15)
        try:
            trends = paginator.page(page)
        except PageNotAnInteger:
            trends = paginator.page(1)
        except EmptyPage:
            trends = paginator.page(paginator.num_pages)
        return render(request, 'search.html', {'trends': trends})

rhyme/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="SNS for rhymers">
    <meta name="author" content="Tacro Hashimoto">
    <meta property="og:title" content="Rhyme ライム">
    <meta property="og:description" content="全てのコミュニケーションがラップで交わされるSNS">
    {% block meta %}
    {% endblock %}
    <link rel="icon" href="../../../../favicon.ico">

    <title>Rhyme</title>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <!-- custom stylesheet -->
    <link rel="stylesheet" href="{% static 'rhyme/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'rhyme/css/ex.css' %}">
    <link rel="stylesheet" href="{% static 'rhyme/css/responsive.css' %}">

    {% block css %}
    {% endblock %}

  </head>

  <body>
    <header>
    {% if request.user.is_authenticated %}
        <a class="text-center" href="{% url 'home' %}"><h2>Rhyme</h2></a>
    {% else %}
      <nav class="navbar navbar-expand-lg">
        <div class="container-fluid ">
          <div class="navbar-header">
            <!-- logo -->
            <a href="{% url 'home' %}" class="navbar-brand smooth-scroll">
                <h2>Rhyme</h2>
            </a>
          </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon text-center">&#9776;</span>
            </button>

          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="nav navbar-nav nav-pills ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">Sign up</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    {% endif %}
    </header>
    <div id="space-top"></div>
      {% block content %}

      {% endblock %}
    <div id="space-bottom"></div>
      {% if request.user.is_authenticated %}
        <section id="footer-menu" class="text-center">
          <div class="col-1-5">
            <a href="{% url 'home' %}"><i class="fas fa-home"></i></a>
          </div>
          <div class="col-1-5">
            <a href="{% url 'search' %}"><i class="fas fa-search"></i></a>
          </div>
          <div class="col-1-5">
            <a href="{% url 'verses:create' %}"><i class="fas fa-plus-square"></i></a>
          </div>
          <div class="col-1-5">
            <a href="{% url 'users:notification' request.user.id %}"><i class="fas fa-bell"></i></a>
          </div>
          <div class="col-1-5">
            <a href="{% url 'users:detail' request.user.id %}">
              {% if request.user.icon %}
                <img src="{{ request.user.icon.url }}" class="img-fluid rounded-circle" />
              {% else %}
                <i class="fas fa-user"></i>
              {% endif %}
            </a>
          </div>
        </section>
      {% else %}
        <footer class="text-center text-muted">
          <div class="container px-sm-0">
            <div class="row">
              <div class="col-4">
                <a href="{% url 'help' %}">Help</a>
              </div>
              <div class="col-4">
                <a href="{% url 'privacy' %}">Privacy Policy</a>
              </div>
              <div class="col-4">
                <a href="{% url 'terms' %}">Terms of Conditions</a>
              </div>
              <div class="col-12">
                <p>&copy rhyme.live {% now "Y" %}</p>
              </div>
            </div>
          </div>
        </footer>
      {% endif %}



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <!-- For infinite scroll -->
    <script src="{% static 'rhyme/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'rhyme/js/infinite.min.js' %}"></script>
    <!-- For pull to refresh -->
    <script src="{% static 'rhyme/js/pulltorefresh.min.js' %}"></script>
    <!-- Custom js -->
    <script src="{% static 'rhyme/js/script.js' %}"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

rhyme/templates/help.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block meta %}
<meta name="twitter:card" content="summary">
<meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'rhyme/img/rhymer_live.jpg' %}">
{% endblock %}
{% block content %}
<section id="help">
  <div class="content-box-lg">
    <div class="heading">
      <h2>FAQ</h2>
    </div>
        <div class="faq">
          <h3><span>Q. </span>サイト利用は無料ですか？登録なしでも見れますか？</h3>
          <h4>
            <span>A. </span>無料です。登録なしでもご覧いただけます。
          </h4>
        </div>
        <div class="faq">
         <h3><span>Q. </span>何を投稿すればいいの？</h3>
         <h4>
           <span>A. </span>日々感じている思いやあなたの考えを、熱いライムにしたためて投稿してください。
         </h4>
        </div>
        <div class="faq">
         <h3><span>Q. </span>DISもありなのですか？</h3>
         <h4>
           <span>A. </span>「DISは愛があるゆえ」という般若さんの言葉を忘れず、リスペクトを持ってディスりましょう。
         </h4>
        </div>
         <div class="faq">
           <h3><span>Q. </span>Beatを投稿して、みんなに使ってほしいだけど</h3>
           <h4>
             <span>A. </span>今後、皆様の声に合わせて機能をアップデートして参ります。ぜひ色んなご意見をお寄せください。
           </h4>
        </div>
      <div class="heading">
        <h2>Contact</h2>
      </div>
      <div class="contact-list">
        <h5>サービスに関するご意見ご要望、または質問などございましたら、以下までご連絡をお願いします。</h5>
        <div>
          <!-- <h5>Instagram: </h5> -->
          <h5>Twitter : <a href="https://twitter.com/tacro_" target="_blank">@tacro_</a></h5>
          <h5>メール : support@rhyme.live</h5>
       </div>
      </div>
      <div class="heading">
        <h2>Special Thanks</h2>
      </div>
      <div id="special-thanks">
        <div class="contact-list">
          <h5>BeatはPIANO FLAVAさまの作品をご好意で使用させてもらっています。<br/>ぜひ他の作品もチェックしてみてください。</h5>
          <div>
            <h5>Twitter : <a href="https://twitter.com/piano_flava" target="_blank">@piano_flava</a></h5>
            <h5>Sound Cloud : <a href="https://soundcloud.com/piano_flava" target="_blank">PIANO FLAVA</a></h5>
            <h5>WEB : <a href="https://piano-flava.com/" target="_blank">PIANO FLAVA Official Weblog</a></h5>
         </div>
        </div>
      </div>
    </div>
  </section>
  {% endblock %}

rhyme/templates/search.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block meta %}
<meta name="twitter:card" content="summary">
<meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'rhyme/img/rhymer_live.jpg' %}">
{% endblock %}
{% load staticfiles %}

{% block content %}

<section id="search">
  <div class="content-box-sm">
    <div class="container text-center">
    <h2>Search</h2>
    <form method="POST" action="{% url 'search' %}">
      {% csrf_token %}
      <div class="form-group">
        <div class="row no-gutters">
          <div class="offset-lg-1"></div>
          <div class="col-lg-8 col-9">
            <input type="text" class="form-control" placeholder="Search verses" name="w">
          </div>
          <div class="col-lg-2 col-3">
            <button class="btn btn-general btn-black fas" type="submit"><i class="fas fa-search"></i></button>
          </div>
          <div class="offset-lg-1"></div>
        </div>
      </div>
    </form>
    </div>

  <div class="container-fluid pt-2">
    {% if results %}
      <div class="infinite-container">
      {% for result in results %}
      <div class="row verse infinite-item">
        <div class="col-2" id="verse-left">
          {% if result.rhymer.icon %}
            <a href="{% url 'users:detail' result.rhymer.id %}">
              <img src="{{ result.rhymer.icon.url }}" class="img-fluid rounded-circle float-right" alt="user's icon">
            </a>
          {% else %}
            <a href="{% url 'users:detail' result.rhymer.id %}">
              <img src="{% static 'users/img/default_icon.png' %}" class="img-fluid rounded-circle float-right" alt="user's icon">
            </a>
          {% endif %}
        </div>
        <div class="col-10" id="verse-right">
            <div class="row">
              <div class="col-12" id="verse-rhymer">
                {% if result.rhymer.mcname %}
                <a href="{% url 'users:detail' result.rhymer.id %}">
                  <h5>{{ result.rhymer.mcname }} </h5>
                  <h6>a.k.a. {{ result.rhymer.username}}</h6>
                </a>
                {% else %}
                <a href="{% url 'users:detail' result.rhymer.id %}">
                  <h5>{{ result.rhymer.username}} </h5>
                </a>
                {% endif %}
              </div>
              <div class="col-12" id="verse-body">
                <a href="{% url 'verses:detail' result.id %}"><p>{{ result.body|linebreaks }}</p></a>
              </div>
              <div class="offset-lg-1"></div>
              <div class="col-3 col-lg-2 verse-reaction"><a href="{% url 'verses:answer' result.id %}"><i class="fas fa-reply"></i> {{ result.get_answers.count }}</a></div>
              <div class="col-3 col-lg-2 verse-reaction"><a href="{% url 'verses:beef' result.id %}"><i class="fas fa-bolt"></i> {{ result.get_beefs.count }}</a></div>
              <div class="col-3 col-lg-2 verse-reaction">
                <a class="like-btn" data-href="{{ result.get_api_like_url }}" data-likes="{{ result.likes.count }}" href="{{ result.get_like_url }}" verse-id = "{{ result.id }}">
                  <i class="fas fa-hand-peace"></i><span id="{{ result.like_text_id }}"> {{ result.likes.count }}</span>
                </a>
              </div>
              <div class="col-3 col-lg-2 verse-reaction"><i class="fas fa-ellipsis-h"></i></div>
              <div class="offset-lg-1"></div>
            </div>
        </div>
      </div>
      {% endfor %}
    </div>

    {% if results.has_next %}
    <a class="infinite-more-link" href="?page={{ results.next_page_number }}"></a>
    {% endif %}

    <div class="loading text-center" style="display: none;">
     <img src="{% static 'rhyme/img/loading.gif' %}" alt="Loading...">
    </div>

    {% else %}
    <div class="infinite-container">
      {% for trend in trends %}
      <div class="row verse infinite-item">
        <div class="col-2" id="verse-left">
          {% if trend.rhymer.icon %}
            <a href="{% url 'users:detail' trend.rhymer.id %}">
              <img src="{{ trend.rhymer.icon.url }}" class="img-fluid rounded-circle float-right" alt="user's icon">
            </a>
          {% else %}
            <a href="{% url 'users:detail' trend.rhymer.id %}">
              <img src="{% static 'users/img/default_icon.png' %}" class="img-fluid rounded-circle float-right" alt="user's icon">
            </a>
          {% endif %}
        </div>
        <div class="col-10" id="verse-right">
            <div class="row">
              <div class="col-12" id="verse-rhymer">
                {% if trend.rhymer.mcname %}
                <a href="{% url 'users:detail' trend.rhymer.id %}">
                  <h5>{{ trend.rhymer.mcname }} </h5>
                  <h6>a.k.a. {{ trend.rhymer.username}}</h6>
                </a>
                {% else %}
                <a href="{% url 'users:detail' trend.rhymer.id %}">
                  <h5>{{ trend.rhymer.username}} </h5>
                </a>
                {% endif %}
              </div>
              <div class="col-12" id="verse-body">
                <a href="{% url 'verses:detail' trend.id %}"><p>{{ trend.body|linebreaks }}</p></a>
              </div>
              <div class="offset-lg-1"></div>
              <div class="col-3 col-lg-2 verse-reaction"><a href="{% url 'verses:answer' trend.id %}"><i class="fas fa-reply"></i> {{ trend.get_answers.count }}</a></div>
              <div class="col-3 col-lg-2 verse-reaction"><a href="{% url 'verses:beef' trend.id %}"><i class="fas fa-bolt"></i> {{ trend.get_beefs.count }}</a></div>
              <div class="col-3 col-lg-2 verse-reaction">
                <a class="like-btn" data-href="{{ trend.get_api_like_url }}" data-likes="{{ trend.likes.count }}" href="{{ trend.get_like_url }}" verse-id = "{{ trend.id }}">
                  <i class="fas fa-hand-peace"></i><span id="{{ trend.like_text_id }}"> {{ trend.likes.count }}</span>
                </a>
              </div>
              <div class="col-3 col-lg-2 verse-reaction"><i class="fas fa-ellipsis-h"></i></div>
              <div class="offset-lg-1"></div>
            </div>
        </div>
      </div>
      {% endfor %}
    </div>

    {% if trends.has_next %}
    <a class="infinite-more-link" href="?page={{ trends.next_page_number }}"></a>
    {% endif %}

    <div class="loading text-center" style="display: none;">
     <img src="{% static 'rhyme/img/loading.gif' %}" alt="Loading...">
    </div>

    {% endif %}
  </div>
</section>


{% endblock %}

rhyme/templates/timeline.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta %}
<meta name="twitter:card" content="summary">
<meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'rhyme/img/rhymer_live.jpg' %}">
{% endblock %}
{% block css %}
  <!-- Stylesheet for verses app -->
  <link rel="stylesheet" href="{% static 'verses/css/verses.css' %}">
  <link rel="stylesheet" href="{% static 'verses/css/verses-responsive.css' %}">
{% endblock %}

{% block content %}

<section id="verses-index">
  <div class="container-fluid pt-2">
    <div class="infinite-container">
      {% for verse in verses %}
      <div class="row verse infinite-item">
        <div class="col-2" id="verse-left">
          {% if verse.rhymer.icon %}
            <a href="{% url 'users:detail' verse.rhymer.id %}">
              <img src="{{ verse.rhymer.icon.url }}" class="img-fluid rounded-circle float-right" alt="user's icon">
            </a>
          {% else %}
            <a href="{% url 'users:detail' verse.rhymer.id %}">
              <img src="{% static 'users/img/default_icon.png' %}" class="img-fluid rounded-circle float-right" alt="user's icon">
            </a>
          {% endif %}
        </div>
        <div class="col-10" id="verse-right">
            <div class="row">
              <div class="col-12" id="verse-rhymer">
                {% if verse.rhymer.mcname %}
                <a href="{% url 'users:detail' verse.rhymer.id %}">
                  <h5>{{ verse.rhymer.mcname }} </h5>
                  <h6>a.k.a. {{ verse.rhymer.username}}</h6>
                </a>
                {% else %}
                <a href="{% url 'users:detail' verse.rhymer.id %}">
                  <h5>{{ verse.rhymer.username}} </h5>
                </a>
                {% endif %}
              </div>
              <div class="col-12" id="verse-body">
                <a href="{% url 'verses:detail' verse.id %}"><p>{{ verse.body|linebreaks }}</p></a>
              </div>
              <div class="offset-lg-1"></div>
              <div class="col-3 col-lg-2 verse-reaction"><a href="{% url 'verses:answer' verse.id %}"><i class="fas fa-reply"></i> {{ verse.get_answers.count }}</a></div>
              <div class="col-3 col-lg-2 verse-reaction"><a href="{% url 'verses:beef' verse.id %}"><i class="fas fa-bolt"></i> {{ verse.get_beefs.count }}</a></div>
              <div class="col-3 col-lg-2 verse-reaction">
                <a class="like-btn" data-href="{{ verse.get_api_like_url }}" data-likes="{{ verse.likes.count }}" href="{{ verse.get_like_url }}" verse-id = "{{ verse.id }}">
                  <i class="fas fa-hand-peace"></i><span id="{{ verse.like_text_id }}"> {{ verse.likes.count }}</span>
                </a>
              </div>
              {% if verse.rhymer == request.user %}
                <div class="col-3 col-lg-2 verse-reaction">
                  <a onclick="return confirm('このバースを削除しますか？')" href="{% url 'verses:delete' verse.id %}">
                    <i class="fas fa-trash-alt"></i>
                  </a>
                </div>
              {% endif %}
              <div class="offset-lg-1"></div>
            </div>
        </div>
      </div>
      {% endfor %}
    </div>

    {% if verses.has_next %}
    <a class="infinite-more-link" href="?page={{ verses.next_page_number }}"></a>
    {% endif %}

    <div class="loading text-center" style="display: none;">
     <img src="{% static 'rhyme/img/loading.gif' %}" alt="Loading...">
    </div>

  </div>
</section>

{% endblock %}

{% block js %}
<script>
  pullRefresh("#verses-index", "")
</script>
{% endblock %}