beats/urls.py
from django.urls import path
from . import views

app_name = 'beats'

urlpatterns = [
]

rhyme/urls.py
from django.contrib import admin
from django.urls import path, include
from rhyme import views
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('verses/', include('verses.urls')),
    path('beats/', include('beats.urls')),
    path('rhymers/', include('users.urls')),
    path('notifications/', include('notifications.urls')),
    path('', views.home, name='home'),
    path('help/', views.help, name='help'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('search/', views.search, name='search'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('<int:user_id>',  views.detail, name = 'detail'),
    path('<int:user_id>/likes',  views.likes, name = 'likes'),
    path('<int:user_id>/edit', views.edit, name = 'edit'),
    path('<int:user_id>/follow', views.follow, name = 'follow'),
    path('<int:user_id>/unfollow', views.unfollow, name = 'unfollow'),
    path('<int:user_id>/followers', views.show_followers, name = 'followers'),
    path('<int:user_id>/follows', views.show_follows, name = 'follows'),
    path('<int:user_id>/notification', views.notification, name='notification'),
]

verses/urls.py
from django.urls import path
from . import views
from .views import PostLikeToggle, PostLikeAPIToggle

app_name = 'verses'

urlpatterns = [
    path('create/',  views.create, name = 'create'),
    path('index/', views.index, name='index'),
    path('<int:verse_id>',views.detail, name='detail'),
    path('<int:verse_id>/delete',views.delete, name='delete'),
    path('<int:verse_id>/like/',PostLikeToggle.as_view(), name='like'),
    path('api/<int:verse_id>/like/',PostLikeAPIToggle.as_view(), name='like-api'),
    path('<int:verse_id>/answer/',views.answer, name = 'answer'),
    path('<int:verse_id>/beef/',views.beef, name = 'beef'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail

class User(AbstractBaseUser, PermissionsMixin):
    #username
    username_validator = ASCIIUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length = 50,
        unique = True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    #mcname
    mcname = models.CharField(
        _('MC name'),
        max_length = 50,
        unique = False,
        blank = True,
    )
    #Email
    email = models.EmailField(_('email address'))
    icon = models.ImageField(_('icon'), upload_to = 'images/icons', null=True, blank=True)
    biography = models.CharField(max_length = 150, blank=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email',]

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        db_table = 'users'

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def get_follows(self):
        relations = Relationship.objects.filter(follower=self)
        return [relation.follow for relation in relations]

    def get_followers(self):
        relations = Relationship.objects.filter(follow=self)
        return [relation.follower for relation in relations]

"""
    def get_index_url(self):
        return "/verses/index/{}".format(self.id)
"""


'''
medium table to connect follow/follower
'''
class Relationship(models.Model):
    follow = models.ForeignKey(User,
        on_delete = models.CASCADE,
        related_name = 'follows')
    follower = models.ForeignKey(User,
        on_delete = models.CASCADE,
        related_name = 'followers')

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import User, Relationship
from verses.models import Verse
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.models import User
# notificatons
from notifications.signals import notify
from notifications.models import Notification
# infinite scroll
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def detail(request, user_id):
    user = get_object_or_404(User, pk = user_id)
    page = request.GET.get('page',1)
    posts_list = Verse.objects.filter(rhymer=user).order_by('-pub_date')
    paginator = Paginator(posts_list, 10)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    followees = user.get_follows() # those who user follows
    followers = user.get_followers() # those who following user
    return render(request, 'users/detail.html', {'user':user, 'posts':posts, 'follows':len(followees), 'followers':len(followers)})

def likes(request, user_id):
    user = get_object_or_404(User, pk = user_id)
    page = request.GET.get('page',1)
    likes_list = Verse.objects.filter(likes = user).order_by('-pub_date')
    paginator = Paginator(likes_list, 10)
    try:
        likes = paginator.page(page)
    except PageNotAnInteger:
        likes = paginator.page(1)
    except EmptyPage:
        likes = paginator.page(paginator.num_pages)
    followees = user.get_follows() # those who user follows
    followers = user.get_followers() # those who following user
    return render(request, 'users/likes.html', {'user':user, 'likes':likes, 'follows':len(followees), 'followers':len(followers)})

@login_required
def edit(request, user_id):
    user = get_object_or_404(User, pk = user_id)
    if user == request.user:
        if request.method == 'POST':
            if request.POST['username']:
                user.username = request.POST['username']
            if request.POST['mcname']:
                user.mcname = request.POST['mcname']
            if request.POST['biography']:
                user.biography = request.POST['biography']
            if request.POST['email']:
                user.email = request.POST['email']
            if 'icon' in request.FILES:
                user.icon = request.FILES['icon']
            user.save()
            return redirect('/rhymers/' + str(user_id))
        else:
            return render(request, 'users/edit.html', {'user':user})
    else:
        return render(request, 'verses/index.html', {'error': 'You are not allowed to this page'})

@login_required
def follow(request, user_id):
    # specify who followee is
    followee = get_object_or_404(User, pk=user_id)
    # specify who follower is
    follower = request.user
    # make sure that they aren't identical
    if follower != followee:
        # check if that follower has already followed the user
        for followeeOfFollower in follower.get_follows():
            if followeeOfFollower == followee:
                # "do nothing and back to previous page
                return redirect('/verses/index')
        # make new relationship between them
        relationship = Relationship(follow = followee, follower = follower, )
        relationship.save()
        notify.send(follower, recipient = followee, verb = ' followed you:', action_object=follower, target=followee, description = 'follow')
        # back to previous page
        return redirect('/rhymers/' + str(user_id))
    else:
        return redirect('/verses/index')

@login_required
def unfollow(request, user_id):
    followee = get_object_or_404(User, pk=user_id)
    follower = request.user
    relationship = Relationship.objects.filter(follow = followee, follower = follower)
    if relationship:
        relationship.delete()
        return redirect('/rhymers/' + str(user_id))
    else:
        return redirect('/verses/index')

def show_follows(request, user_id):
    user = get_object_or_404(User, pk = user_id)
    page = request.GET.get('page',1)
    # get those who user follows
    followees_list = user.get_follows()
    paginator = Paginator(followees_list, 10)
    try:
        followees = paginator.page(page)
    except PageNotAnInteger:
        followees = paginator.page(1)
    except EmptyPage:
        followees = paginator.page(paginator.num_pages)
    return render(request, 'users/show_follows.html', {'followees':followees})


def show_followers(request, user_id):
    user = get_object_or_404(User, pk = user_id)
    page = request.GET.get('page',1)
    # get those who follow user
    followers_list = user.get_followers()
    paginator = Paginator(followers_list, 10)
    try:
        followers = paginator.page(page)
    except PageNotAnInteger:
        followers = paginator.page(1)
    except EmptyPage:
        followers = paginator.page(paginator.num_pages)
    return render(request, 'users/show_followers.html', {'followers':followers})

@login_required
def notification(request, user_id):
    user = get_object_or_404(User, pk = user_id)
    if user == request.user:
        notifications_list = Notification.objects.filter(recipient = user).order_by('-timestamp')
        page = request.GET.get('page',1)
        paginator = Paginator(notifications_list, 8)
        try:
            notifications = paginator.page(page)
        except PageNotAnInteger:
            notifications = paginator.page(1)
        except EmptyPage:
            notifications = paginator.page(paginator.num_pages)
        return render(request, 'users/notification.html', {'user':user, 'notifications':notifications})
    else:
        return render(request, 'verses/index.html', {'error': 'You are not allowed to this page'})

users/templates/users/detail.html
{% extends 'base.html' %}
{% load account socialaccount %}
{% load staticfiles %}
{% block meta %}
<meta name="twitter:card" content="summary">
{% if user.icon %}
<meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{{ user.icon.url }}">
{% else %}
<meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'users/img/default_icon.png' %}">
{% endif %}
{% endblock %}
{% block css %}
  <!-- Stylesheet for users app -->
  <link rel="stylesheet" href="{% static 'users/css/users.css' %}">
  <link rel="stylesheet" href="{% static 'users/css/users-responsive.css' %}">
{% endblock %}
{% block content %}

<section id="user-mypage">
  <div class="container">

    <!-- Popup menu for setting and logout, cancellation -->
    <div class="popup-overlay">
      <div class="popup-content">
        <p id="close-popup" class="text-left"><i class="fas fa-times"></i></p>
        <a href="{% provider_login_url "twitter" process="connect" %}"><p>Connect a Twitter account</p></a>
        <a href="{% url 'account_logout' %}"><p>Log Out</p></a>
        <a href="{% url 'account_change_password' %}"><p>Change Password</p></a>
        <a href="{% url 'privacy' %}"><p>Privacy Policy</p></a>
        <a href="{% url 'terms' %}"><p>Terms of Conditions</p></a>
      </div>
    </div>

    <!-- Contents -->
    <div id="user-info" class="row pt-3">
      <div class="col-3">
        {% if user.icon %}
        <img src="{{ user.icon.url }}" class="img-fluid float-right" />
        {% else %}
        <img src="{% static "users/img/default_icon.png" %}" class="img-fluid float-right" alt="he doesn't have icon" />
        {% endif %}
      </div>
      <div class="col-9">
        <div class="row mx-auto">
          <div class="col-12">
            {% if user.mcname %}
            <h3>{{ user.mcname }}</h5>
            <h5>a.k.a. {{ user.username }}</h5>
            {% else %}
            <h5>{{user.username}}</h5>
            {% endif %}
          </div>
          <div class="col-12">
            <p>{{user.biography}}</p>
          </div>
          <div class="col-6">
            <a href="{% url 'users:followers' user.id %}"><span>{{ followers }}</span> FOLLOWERS</a>
          </div>
          <div class="col-6">
            <a href="{% url 'users:follows' user.id %}"><span>{{ follows }}</span> FOLLOWS</a>
          </div>
          <div class="col-12 my-3">
            {% if user != request.user %}
              {% if user in request.user.get_follows %}
                <a href="{% url 'users:unfollow' user.id %}" class="btn btn-general btn-yellow" role="button" value="following">following</a>
              {% else %}
                <a href="{% url 'users:follow' user.id %}" class="btn btn-general btn-yellow" role="button" value="follow">follow</a>
              {% endif %}
            {% else %}
              <a class="btn btn-general btn-black" href="{% url 'users:edit' user.id %}" role="button" value="Edit Profile">Edit Profile</a>
              <i id="open-popup" class="fas fa-cog"></i>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    <!-- Tabs to switch posts/likes -->
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a href="#posts" class="nav-link active">Verses</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'users:likes' user.id %}" class="nav-link">Likes</a>
      </li>
    </ul>

      <!-- Posts -->
      <div id="posts">
        <div class="row pt-3">
          <div class="col-12">
            <div class="infinite-container">
              {% for post in posts %}
              <div class="row post infinite-item">
                <div class="col-2" id="post-left">
                  {% if post.rhymer.icon %}
                  <a href="{% url 'users:detail' post.rhymer.id %}">
                    <img src="{{ post.rhymer.icon.url }}" class="img-fluid rounded-circle float-right" alt="user's icon">
                  </a>
                  {% else %}
                  <a href="{% url 'users:detail' post.rhymer.id %}">
                    <img src="{% static 'users/img/default_icon.png' %}" class="img-fluid rounded-circle float-right" alt="user's icon">
                  </a>
                  {% endif %}
                </div>
                <div class="col-10" id="post-right">
                    <div class="row">
                      <div class="col-12" id="post-rhymer">
                        <a href="{% url 'users:detail' post.rhymer.id %}">
                        {% if post.rhymer.mcname %}
                          <h5>{{ post.rhymer.mcname }} </h5>
                          <h6>a.k.a. {{ post.rhymer.username}}</h6>
                        {% else %}
                          <h5>{{ post.rhymer.username}} </h5>
                        {% endif %}
                        </a>
                      </div>
                      <div class="col-12" id="post-body">
                        <a href="{% url 'verses:detail' post.id %}">
                          <p>{{ post.body|linebreaks }}</p>
                        </a>
                      </div>
                      <div class="offset-lg-1"></div>
                      <div class="col-3 col-lg-2 post-reaction"><a href="{% url 'verses:answer' post.id %}"><i class="fas fa-reply"></i> {{ post.get_answers.count }}</a></div>
                      <div class="col-3 col-lg-2 post-reaction"><a href="{% url 'verses:beef' post.id %}"><i class="fas fa-bolt"></i> {{ post.get_beefs.count }}</a></div>
                      <div class="col-3 col-lg-2 post-reaction">
                        <a class="like-btn" data-href="{{ post.get_api_like_url }}" data-likes="{{ post.likes.count }}" href="{{ post.get_like_url }}" verse-id = "{{ post.id }}">
                          <i class="fas fa-hand-peace"></i><span id="{{ post.like_text_id }}"> {{ post.likes.count }}</span>
                        </a>
                      </div>
                      {% if post.rhymer == request.user %}
                        <div class="col-3 col-lg-2 post-reaction">
                          <a onclick="return confirm('このバースを削除しますか？')" href="{% url 'verses:delete' post.id %}">
                            <i class="fas fa-trash-alt"></i>
                          </a>
                        </div>
                      {% endif %}
                      <div class="offset-lg-1"></div>
                    </div>
                </div>
              </div>
              {% endfor %}
            </div>

            {% if posts.has_next %}
            <a class="infinite-more-link" href="?page={{ posts.next_page_number }}"></a>
            {% endif %}

            <div class="loading text-center" style="display: none;">
             <img src="{% static 'rhyme/img/loading.gif' %}" alt="Loading...">
            </div>

          </div>
        </div>
      </div>
  </div>

</section>

{% endblock %}
{% block js %}
<script src="{% static 'users/js/users.js' %}"></script>
<script>
  pullRefresh("#user-mypage", "{% url 'users:detail' user.id %}")
</script>
{% endblock %}

users/templates/users/likes.html
{% extends 'base.html' %}
{% load account socialaccount %}
{% load staticfiles %}
{% block meta %}
<meta name="twitter:card" content="summary">
{% if user.icon %}
<meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{{ user.icon.url }}">
{% else %}
<meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'users/img/default_icon.png' %}">
{% endif %}
{% endblock %}
{% block css %}
  <!-- Stylesheet for users app -->
  <link rel="stylesheet" href="{% static 'users/css/users.css' %}">
  <link rel="stylesheet" href="{% static 'users/css/users-responsive.css' %}">
{% endblock %}
{% block content %}

<section id="user-mypage-likes">
  <div class="container">

    <!-- Popup menu for setting and logout, cancellation -->
    <div class="popup-overlay">
      <div class="popup-content">
        <p id="close-popup" class="text-left"><i class="fas fa-times"></i></p>
        <a href="{% provider_login_url "twitter" process="connect" %}"><p>Connect a Twitter account</p></a>
        <a href="{% url 'account_logout' %}"><p>Log Out</p></a>
        <a href="{% url 'account_change_password' %}"><p>Change Password</p></a>
        <a href="{% url 'privacy' %}"><p>Privacy Policy</p></a>
        <a href="{% url 'terms' %}"><p>Terms of Conditions</p></a>
      </div>
    </div>

    <!-- Contents -->
    <div id="user-info" class="row pt-3">
      <div class="col-3">
        {% if user.icon %}
        <img src="{{ user.icon.url }}" class="img-fluid float-right" />
        {% else %}
        <img src="{% static "users/img/default_icon.png" %}" class="img-fluid float-right" alt="he doesn't have icon" />
        {% endif %}
      </div>
      <div class="col-9">
        <div class="row mx-auto">
          <div class="col-12">
            {% if user.mcname %}
            <h3>{{ user.mcname }}</h5>
            <h5>a.k.a. {{ user.username }}</h5>
            {% else %}
            <h5>{{user.username}}</h5>
            {% endif %}
          </div>
          <div class="col-12">
            <p>{{user.biography}}</p>
          </div>
          <div class="col-6">
            <a href="{% url 'users:followers' user.id %}"><span>{{ followers }}</span> FOLLOWERS</a>
          </div>
          <div class="col-6">
            <a href="{% url 'users:follows' user.id %}"><span>{{ follows }}</span> FOLLOWS</a>
          </div>
          <div class="col-12 my-3">
            {% if user != request.user %}
              {% if user in request.user.get_follows %}
                <a href="{% url 'users:unfollow' user.id %}" class="btn btn-general btn-yellow" role="button" value="following">following</a>
              {% else %}
                <a href="{% url 'users:follow' user.id %}" class="btn btn-general btn-yellow" role="button" value="follow">follow</a>
              {% endif %}
            {% else %}
              <a class="btn btn-general btn-black" href="{% url 'users:edit' user.id %}" role="button" value="Edit Profile">Edit Profile</a>
              <i id="open-popup" class="fas fa-cog"></i>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    <!-- Tabs to switch posts/likes -->
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a href="{% url 'users:detail' user.id %}" class="nav-link">Verses</a>
      </li>
      <li class="nav-item">
        <a href="#likes" class="nav-link active">Likes</a>
      </li>
    </ul>

      <!-- likes -->
      <div id="likes">
        <div class="row pt-3">
          <div class="col-12">
            <div class="infinite-container">
              {% for like in likes %}
              <div class="row post infinite-item">
                <div class="col-2" id="post-left">
                  {% if like.rhymer.icon %}
                  <a href="{% url 'users:detail' like.rhymer.id %}">
                    <img src="{{ like.rhymer.icon.url }}" class="img-fluid rounded-circle float-right" alt="user's icon">
                  </a>
                  {% else %}
                  <a href="{% url 'users:detail' like.rhymer.id %}">
                    <img src="{% static 'users/img/default_icon.png' %}" class="img-fluid rounded-circle float-right" alt="user's icon">
                  </a>
                  {% endif %}
                </div>
                <div class="col-10" id="post-right">
                    <div class="row">
                      <div class="col-12" id="post-rhymer">
                        <a href="{% url 'users:detail' like.rhymer.id %}">
                        {% if like.rhymer.mcname %}
                          <h5>{{ like.rhymer.mcname }} </h5>
                          <h6>a.k.a. {{ like.rhymer.username}}</h6>
                        {% else %}
                          <h5>{{ like.rhymer.username}} </h5>
                        {% endif %}
                        </a>
                      </div>
                      <div class="col-12" id="post-body">
                        <a href="{% url 'verses:detail' like.id %}">
                          <p>{{ like.body|linebreaks }}</p>
                        </a>
                      </div>
                      <div class="offset-lg-1"></div>
                      <div class="col-3 col-lg-2 post-reaction"><a href="{% url 'verses:answer' like.id %}"><i class="fas fa-reply"></i> {{ like.get_answers.count }}</a></div>
                      <div class="col-3 col-lg-2 post-reaction"><a href="{% url 'verses:beef' like.id %}"><i class="fas fa-bolt"></i> {{ like.get_beefs.count }}</a></div>
                      <div class="col-3 col-lg-2 post-reaction"><a class="like-btn" data-href="{{ like.get_api_like_url }}" data-likes="{{ like.likes.count }}" href="{{ like.get_like_url }}"><i class="fas fa-hand-peace"></i><span class="like-text"> {{ like.likes.count }}</span></a></div>
                      {% if like.rhymer == request.user %}
                        <div class="col-3 col-lg-2 post-reaction">
                          <a onclick="return confirm('このバースを削除しますか？')" href="{% url 'verses:delete' like.id %}">
                            <i class="fas fa-trash-alt"></i>
                          </a>
                        </div>
                      {% endif %}
                      <div class="offset-lg-1"></div>
                    </div>
                </div>
              </div>
              {% endfor %}
            </div>

            {% if likes.has_next %}
            <a class="infinite-more-link" href="?page={{ likes.next_page_number }}"></a>
            {% endif %}

            <div class="loading text-center" style="display: none;">
             <img src="{% static 'rhyme/img/loading.gif' %}" alt="Loading...">
            </div>

          </div>
        </div>
      </div>
  </div>

</section>

{% endblock %}
{% block js %}
<script src="{% static 'users/js/users.js' %}"></script>
<script>
  pullRefresh("#user-mypage-likes", "{% url 'users:likes' user.id %}")
</script>
{% endblock %}

users/templates/users/show_followers.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta %}
<meta name="twitter:card" content="summary">
<meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'rhyme/img/rhymer_live.jpg' %}">
{% endblock %}
{% block css %}
  <!-- Stylesheet for users app -->
  <link rel="stylesheet" href="{% static 'users/css/users.css' %}">
  <link rel="stylesheet" href="{% static 'users/css/users-responsive.css' %}">

{% endblock %}
{% block content %}

<div id="followers">
  <div class="container-fluid">
    <div class="infinite-container">
    {% for follower in followers %}
    <div class="user-summary infinite-item">
      <div class="row">
        <div class="offset-lg-1"></div>
        <div class="col-3 col-sm-2 col-lg-2">
          <a href="{% url 'users:detail' follower.id %}">
            {% if follower.icon %}
              <img src="{{ follower.icon.url }}" alt="icon" class="img-fluid float-right">
            {% else %}
              <img src="{% static "users/img/default_icon.png" %}" alt="icon" class="img-fluid float-right">
            {% endif %}
          </a>
        </div>
        <div id="user-summary-center" class="col-5 col-sm-6 col-lg-5">
          <a href="{% url 'users:detail' follower.id %}">
              {% if follower.mcname %}
              <h5>{{ follower.mcname }}</h5>
              <h6>a.k.a. {{ follower.username }}</h6>
              {% else %}
              <h5>{{ follower.username }}</h5>
              {% endif %}
          </a>
        </div>
        <div class="col-4" id="user-summary-right">
          <div class="follow-btn">
            {% if follower != request.user %}
              {% if follower in request.user.get_follows %}
                <a href="{% url 'users:unfollow' follower.id %}" class="btn btn-general btn-yellow btn-following" role="button" value="following">following</a>
              {% else %}
                <a href="{% url 'users:follow' follower.id %}" class="btn btn-general btn-follow" role="button" value="follow">follow</a>
              {% endif %}
            {% endif %}
          </div>
        </div>
        <div class="offset-lg-1"></div>
      </div>
    </div>
    {% endfor %}
    </div>

    {% if followers.has_next %}
    <a class="infinite-more-link" href="?page={{ followers.next_page_number }}"></a>
    {% endif %}

    <div class="loading mx-auto" style="display: none;">
     <img src="{% static 'rhyme/img/loading.gif' %}" alt="Loading...">
    </div>

  </div>
</div>

{% endblock %}
{% block js %}
<script src="{% static 'users/js/users.js' %}"></script>
{% endblock %}

users/templates/users/show_follows.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta %}
<meta name="twitter:card" content="summary">
<meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'rhyme/img/rhymer_live.jpg' %}">
{% endblock %}
{% block css %}
  <!-- Stylesheet for users app -->
  <link rel="stylesheet" href="{% static 'users/css/users.css' %}">
  <link rel="stylesheet" href="{% static 'users/css/users-responsive.css' %}">

{% endblock %}
{% block content %}

<div id="followees">
  <div class="container-fluid">
    <div class="infinite-container">
    {% for followee in followees %}
    <div class="user-summary infinite-item">
      <div class="row">
        <div class="offset-lg-1"></div>
        <div class="col-3 col-sm-2 col-lg-2">
          <a href="{% url 'users:detail' followee.id %}">
            {% if followee.icon %}
              <img src="{{ followee.icon.url }}" alt="icon" class="img-fluid float-right">
            {% else %}
              <img src="{% static "users/img/default_icon.png" %}" alt="icon" class="img-fluid float-right">
            {% endif %}
          </a>
        </div>
        <div id="user-summary-center" class="col-5 col-sm-6 col-lg-5">
          <a href="{% url 'users:detail' followee.id %}">
              {% if followee.mcname %}
              <h5>{{ followee.mcname }}</h5>
              <h6>a.k.a. {{ followee.username }}</h6>
              {% else %}
              <h5>{{ followee.username }}</h5>
              {% endif %}
          </a>
        </div>
        <div class="col-4" id="user-summary-right">
          <div class="follow-btn">
            {% if followee != request.user %}
              {% if followee in request.user.get_follows %}
                <a href="{% url 'users:unfollow' followee.id %}" class="btn btn-general btn-yellow btn-following" role="button" value="following">following</a>
              {% else %}
                <a href="{% url 'users:follow' followee.id %}" class="btn btn-general btn-follow" role="button" value="follow">follow</a>
              {% endif %}
            {% endif %}
          </div>
        </div>
        <div class="offset-lg-1"></div>
      </div>
    </div>
    {% endfor %}
    </div>

    {% if followees.has_next %}
    <a class="infinite-more-link" href="?page={{ followees.next_page_number }}"></a>
    {% endif %}

    <div class="loading mx-auto" style="display: none;">
     <img src="{% static 'rhyme/img/loading.gif' %}" alt="Loading...">
    </div>

  </div>
</div>

{% endblock %}
{% block js %}
<script src="{% static 'users/js/users.js' %}"></script>
{% endblock %}